print("""oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo''''oooooooooooooooooooooooooooooooooooooooooooooooooo''''oooooooooooooooooooooooooooo
oooooooooo''''''''''''''''''''''''''''''''''''''''oooooooooooooooooooooooooooooooo'''''''oooooooooooooooooooooooooooooooooooooooooooooY''''''''''''''''''''ooooooooooo
oooooooooo'''ooooooooo'''oooooooooo'''ooooooooo'''ooooooooooooooooooooooooooooooooooooo''''oooooooooooooooooooooooooooooooooooooooooooJ'''QQQQQQQQQQQ00QxI'ooooooooooo
oooooooooo'''ooooooooo'''oooooooooo'''ooooooooo'''oooooooooooooooooooo''i+~~~~~~~~~~~~~~~~~~~~~~~~~~~!''oooooooooooo''>jzYXzzccccccccc('''czzXYYYYYYYYYYYYYYn-''oooooo
oooooooooo'''ooooooooo'''oooooooooo'''ooooooooo'''oooooooooooooooooooo''''''''''''''''''''''''''''''''''oooooooooooo''''''''''''''''''''''''''''''''''''''''''''oooooo
oooooooooo'''ooooooooo'''oooooooooo'''ooooooooo'''oooooooooooooooooooo'''oooooooooooooooooooooooooooo'''oooooooooooo'''oooo(oooooooooooooooooooooooooooop,ooo'''oooooo
oooooooooo''''''''''''''''''''''''''''''''''''''''oooooooooooooooooooo'''oooooooooooooooooooooooooooo'''oooooooooooo'''oooo'''''''''''''''''''''''''''''''ooo'''oooooo
ooooooooooooooooooooooo'oooooooooooooooooooooooooooooooooooooooooooooo'''oooooooooooooooooooooooooooo'''ooooooooooooooooooooou'''ooooo'''''''oooooo'''qooooooooooooooo
ooooooooooooooooooooo'''''oooooooooooooooooooooooooooooooooooooooooooo''''''''''''''''''''''''''''''''''oooooooooooooooooo'''''oooox''''ooo''''oooooo''''''ooooooooooo
oooooooooooooooooooo''''oooooooooooooooooooooooooooooooooooooooooooooo'''oooooooooooooooooooooooooooooooooooooooooooooo''''mooooo''''-ooooooo+''''ooooooo''ooooooooooo
oooooooooooooooooo''''''''''''''''''''''''''''oooooooooooooooooooooooo'''oooooooooooooooooooooooooooooooooooooooooooooooooooo''''''oooooooooooooo''''''ooooooooooooooo
ooooooooooooooo/''''ooooooooooooooooooooo''''ooooooooooooooooooooooooo'''oooooooooooooooooooooooooooooooooooooooooooooooo''''''''''''''''''''''''''''''''''''Joooooooo
ooooooooooooo''''?ooooofoooooooooooooooo''',ooooooooooooooooooooooooo`'''ooo'''''''''''''''''''''''''''''ooooooooo'''''''''o'''oooooooooooooooooooooo'''op'''''''''ooo
ooooooooo''''''oooooo''''''ooooooooooo''''ooooooooooooooooooooooooooo'''oooo'''ooooooooooooooooooooooo'''oooooooooo'''kooooo''''''''''''''''''''''''''''oooooooooooooo
ooooooooooooooooooooooooo'''''vooooo''''oooooooooooooooooooooooooooo'''ooooo'''ooooooooooooooooooooooo'''ooooooooooooooooooo'''oooooooooooooooooooooo'''oooooooooooooo
ooooooooooooooooooooooooooooL'''''''''ooooooooooooooooooooooooooooo'''oooooo'''ooooooooooooooooooooooo'''ooooooooooooooooooo'''rrrrrrrrrrrrrrrrrrrrrr'''oooooooooooooo
oooooooooooooooooooooooooooooo'''''oooooooooooooooooooooooooooooo+'''ooooooo'''ooooooooooooooooooooooo'''ooooooooooooooooooo''';;;;;;;;;;;;;;;;;;;;;;'''oooooooooooooo
oooooooooooooooooooooooo{'''''''ooooooooooooooooooooooooooooooo{''''oooooooo'''''''''''''''''''''''''''''ooooooooooooooooooo'''oooooooooooooooooooooo'''oooooooooooooo
ooooookooooov,''''''''''''<oooooooooooooooooooooooooooooooooo'''''oooooooooo'''ooooooooooooooooooooooo'''ooooooooooooooooooo''''''''''''''''''''''''''''oooooooooooooo
oooooooo'''''''''''ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo'''ooooooooooooooooooooooo'''ooooooooooooooooooo'''oooooooooooooooooooooo'''oooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
""")
